---
- hosts: all
  sudo: True

  tasks:
  - name: install docker-py to use Ansible docker module
    pip: docker-py
    
  - name: Download docker
    shell: wget -qO- https://get.docker.com/ | sh

  - name: Test docker connection
    shell: docker --version
