---
- hosts: master
  sudo: True
  
  tasks:
  - name: pull docker registry
    shell: sudo docker pull registry
    
  - name: run container
    shell: sudo docker run -p 5000:5000 -t myRegistry registry
