---
- hosts: master
  sudo: True
  
  tasks:
  - name: pull docker registry
     docker:
      name: myRegistry
      image: registry
      state: started
      pull: missing
      ports:
      - "5000:5000"
